# Generated by Django 5.2 on 2025-05-05 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['client', 'brand', 'model'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['brand', 'name'], 'verbose_name': 'Part', 'verbose_name_plural': 'Parts'},
        ),
        migrations.RemoveField(
            model_name='part',
            name='minimum_quantity',
        ),
        migrations.RemoveField(
            model_name='part',
            name='model',
        ),
        migrations.RemoveField(
            model_name='part',
            name='quantity',
        ),
        migrations.AddField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='available', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='part',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Quantity'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('repair', 'Repair'), ('maintenance', 'Maintenance'), ('upgrade', 'Upgrade'), ('diagnostic', 'Diagnostic'), ('cleaning', 'Cleaning'), ('other', 'Other')], default='repair', max_length=20, verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('tablet', 'Tablet'), ('phone', 'Phone'), ('printer', 'Printer'), ('other', 'Other')], max_length=20, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='part',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'Graphics Card'), ('RAM', 'Memory'), ('MB', 'Motherboard'), ('PSU', 'Power Supply'), ('HDD', 'Hard Drive'), ('SSD', 'Solid State Drive'), ('OTHER', 'Other')], max_length=10, verbose_name='Part Type'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
