# Generated by Django 5.2 on 2025-05-05 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_repairorder_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='service.part', verbose_name='Part')),
                ('repair_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_usages', to='service.repairorder', verbose_name='Repair Order')),
            ],
            options={
                'verbose_name': 'Part Usage',
                'verbose_name_plural': 'Part Usages',
                'unique_together': {('repair_order', 'part')},
            },
        ),
    ]
