# Generated by Django 5.2 on 2025-05-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_partusage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartUsage',
        ),
    ]
