# Generated by Django 5.2 on 2025-05-06 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_repairorder_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='reserved_parts',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reserved Parts'),
        ),
    ]
