# Generated by Django 5.2 on 2025-05-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_part_status_trigger'),
        ('service', '0009_part_reserved_parts'),
    ]

    operations = [
    ]
